fontArray =  [
  ['control-panel__control-font__item', 'Georgia'],
  ['control-panel__control-font__item', 'Palatino'],
  ['control-panel__control-font__item', 'Times'],
  ['control-panel__control-font__item', 'Helvetica'],
  ['control-panel__control-font__item', 'Arial'],
  ['control-panel__control-font__item', 'Gadget'],
  ['control-panel__control-font__item', 'Comic Sans MS'],
  ['control-panel__control-font__item', 'Impact'],
  ['control-panel__control-font__item', 'Charcoal'],
  ['control-panel__control-font__item', 'Lucida Sans Unicode'],
  ['control-panel__control-font__item', 'Lucida Grande'],
  ['control-panel__control-font__item', 'Tahoma'],
  ['control-panel__control-font__item', 'Geneva'],
  ['control-panel__control-font__item', 'Trebuchet MS'],
  ['control-panel__control-font__item', 'Verdana'],
  ['control-panel__control-font__item', 'Geneva'],
  ['control-panel__control-font__item', 'Courier New'],
  ['control-panel__control-font__item', 'Courier'],
  ['control-panel__control-font__item', 'Lucida Console'],
  ['control-panel__control-font__item', 'Monaco']
];
